### ISSUE TITLE
Contradictory README and wiki post

### ISSUE THREAD

**Issue by Seanny123** [ipa320/cob_people_perception#13]
In your wiki post, you say that to run the program, you should follow these steps:
`roslaunch openni_launch openni.launch`
`roslaunch cob_people_detection people_detection.launch`
`rosrun cob_people_detection people_detection_client`

However, in the wiki, you cite these steps instead:
`roslaunch cob_people_detection openni.launch`
`roslaunch cob_people_detection people_detection.launch`
`rosrun cob_people_detection people_detection_client`

Could you please clarify which one is correct? Both are giving me problems.

**Comment by Seanny123** [comment]
Got it to run by following the wiki post.

**Comment by ipa-rmb** [comment]
Normally it doesn't matter since I only copied the original launch file from the openni_launch package and changed one or two settings of parameters. Actually I recommend to use the `roslaunch openni_launch openni.launch` now since this is always the current version of the Kinect driver and because I added a couple of arguments at the beginning of file `cob_people_detection/ros/launch/people_detection.launch`. You just need to adjust these parameters to the names of your driver. They should be fine already if you are using the standard kinect driver.

Please notice that you might need the newer openni2 driver when you have a newer Asus Xtion Pro Live camera.
