### ISSUE TITLE
Crash and unable to restart on Ubuntu 12.04 32-bit ROS groovy

### ISSUE THREAD

**Issue by Seanny123** [ipa320/cob_people_perception#14]
I ran the program following the steps in the ROS wiki. I ran it once successfully and it crashed as soon as I loaded the recognition model I just built by taking automatic pictures. Now every time I try to run `rosrun cob_people_detection people_detection_client`, I get the error message `No connection to server 'load_model_server'.`.

I think I could correct the issue if you informed me where this model that it reports is stored. I tried looking through the source code and narrowed it down to `loadActionModel.h`, but couldn't find anywhere in the code where a model was being loaded. I would then make a pull request to clarify the error message.

**Comment by ipa-rmb** [comment]
Hi Sean, I just added this import piece of information some days ago at the wiki documentation at the end of the Quick Start section. You may find all the recorded files in your home directory in the hidden folder `~/.ros/cob_people_detection/files/training_data` . If you have trouble just delete all data and the program will start without any problems again.

I probably also know the reason for the program failing to load. We recently introduced a way faster training method that can train a recognition model for hundreds of images within less than a second. The only drawback of this method is that it needs at least two different people to be trained. So after deleting the files, please train two people before stopping the program or before training the recognition model for the first time. Then everything should work well.

**Comment by ipa-rmb** [comment]
The parameter for the recognition method can be set in file `cob_people_detection/ros/launch/face_recognizer_params.yaml` . The name of the parameter is: recognition_method .

Your choices are: 0 = Fisherfaces, 1 = Eigenfaces, 2 = LDA2D, 3 = PCA2D . Attention: choices 0 and 1 work with a single person in the training data, options 2 and 3 will cause a crash of the program if you do not train at least 2 different people.

I have updated the wiki documentation to make people aware of this fact. Thanks for raising this issue!

**Comment by Seanny123** [comment]
I'm glad that my fumbling about had a positive outcome!

**Comment by bachapk** [comment]
Hi
When first time I installed these cob_people packages, everything worked well. But due to some reason it is not working at all. When I run : roslaunch cob_people_detection people_detection.launch OR roslaunch cob_people_detection people_detection.launch using_nodelets:=true it shows nothing in the display window. The display window 
![screenshot from 2016-05-30 14 02 47](https://cloud.githubusercontent.com/assets/19236442/15640961/d9b9a8a0-266f-11e6-9286-452e83d58acc.png) is like this. 
Also when I write this command: rosrun cob_people_detection people_detection_client then it says No connection to server 'load_model_server'. ![screenshot from 2016-05-30 14 03 37](https://cloud.githubusercontent.com/assets/19236442/15640987/06c34824-2670-11e6-8e0f-70362454119f.png)
I am new. Please help what is wrong. My /home/bacha/catkin_ws/src/cob_people_perception/cob_people_detection/common/files/training_data folder is empty.

**Comment by ipa-rmb** [comment]
Hi, sorry for the delayed reply due to my holidays. Can you please tell me whether you use the version that you can install via sudo apt-get install or did you download it from github and build it yourself.

From the log screen I can not tell any error, could you please submit the whole output of the program upon startup (i.e. from the upper image roslaunch cob_people_detection people_detection.launch). I suspect that either not all nodes are running. Or did you recently change your Kinect driver that might deliver other topics now? Did you try to re-install the software?

**Comment by ipa-rmb** [comment]
I just saw your issue #40 and that you could sort out the problems already. Well done, and sorry for the trouble.
